### ISSUE TITLE
COCO Experiments 

### ISSUE THREAD

**Issue by YoruCathy** [j-min/IterInpaint#1]
Hi, thanks for sharing the code. I was trying your demo on hugging face space, but it doesn't work well for the more generalized prompts, for example, the prompts you used in the COCO Examples on the project page. I'm wondering if that experiment uses a different checkpoint. Is it possible to have access to it somewhere?

**Comment by j-min** [comment]
Hi @YoruCathy, thanks for your interest! Since the COCO experiment was from some of our preliminary experiments and not our main focus, we added our CLEVR model first.
But I also plan to add a COCO example (maybe by this weekend). I'll let you know once I add it.

**Comment by j-min** [comment]
Hi @YoruCathy, sorry for the long delay! I haven't had time to revisit this project for a while, but I could finally release the COCO checkpoint of IterInpaint - https://huggingface.co/j-min/iterinpaint_sd15inpaint_coco
